version: '3.3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "JsonTopic:1:1,AvroTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - CLUSTER_NAME=Cluster Name
      - COUNTRY_NAME=Country
      - SERVICE_NAME=producer
    ports:
      - "9001:8080"
    depends_on:
      - zookeeper
      - kafka
    links:
      - kafka


volumes:
  service_db:
