version: '3.3'

services:
  producer_db:
    container_name: producer_mysql
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: 'producer'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33066:3306'
    expose:
      - '3306'
    volumes:
      - service_db:/var/lib/producer_mysqldb

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: docker.for.mac.localhost
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "TestTopic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  producer_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - CLUSTER_NAME=Cluster Name
      - COUNTRY_NAME=Country
      - SERVICE_NAME=producer
      - DB_HOST=producer_db
      - DB_PORT=3306
      - DB_USE_SSL=false
      - DB_NAME=producer
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=HIUFH7yerfhiuerh78498HU
    ports:
      - "9001:8080"
    depends_on:
      - producer_db
      - zookeeper
      - kafka
    links:
      - kafka
      - producer_db

  consumer_app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - CLUSTER_NAME=Cluster Name
      - COUNTRY_NAME=Country
      - SERVICE_NAME=producer
      - DB_HOST=producer_db
      - DB_PORT=3306
      - DB_USE_SSL=false
      - DB_NAME=producer
      - DB_USER=user
      - DB_PASSWORD=password
      - JWT_SECRET=HIUFH7yerfhiuerh78498HU
    depends_on:
      - producer_db
      - zookeeper
      - kafka
    links:
      - kafka
      - producer_db


volumes:
  service_db:
