version: '3.3'

services:
  producer_db:
    container_name: producer_mysql
    image: mysql:5.7.27
    restart: always
    environment:
      MYSQL_DATABASE: 'producer'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '33066:3306'
    expose:
      - '3306'
    volumes:
      - service_db:/var/lib/producer_mysqldb

volumes:
  service_db:
